name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Visual Studio Build Tools
        shell: pwsh
        run: |
          $vsInstallerUrl = "https://aka.ms/vs/17/release/vs_BuildTools.exe"
          $vsInstallerPath = "$env:RUNNER_TEMP\vs_BuildTools.exe"
          $installDir = "C:\MyVS"

          Invoke-WebRequest $vsInstallerUrl -OutFile $vsInstallerPath

          Start-Process -Wait -FilePath $vsInstallerPath -ArgumentList `
            "--installPath `"$installDir`"", `
            "--add Microsoft.Net.ComponentGroup.TargetingPacks", `
            "--add Microsoft.VisualStudio.Workload.VCTools", `
            "--includeRecommended", `
            "--passive", "--norestart", "--wait"

      - name: Install .NET Framework 4.5.1 Developer Pack
        shell: pwsh
        run: |
          $url = "https://download.microsoft.com/download/9/6/0/96075294-6820-4f01-924a-474e0023e407/NDP451-KB2861696-x86-x64-DevPack.exe"
          $devPack = "$env:RUNNER_TEMP\ndp451.exe"
          Invoke-WebRequest $url -OutFile $devPack
          Start-Process -Wait -FilePath $devPack -ArgumentList "/quiet", "/norestart"

      - name: Set up MSVC environment
        shell: cmd
        run: |
          call "C:\MyVS\VC\Auxiliary\Build\vcvars64.bat"

      - name: Clone Celeste_Decompiled
        run: git clone https://github.com/Twig6943/Celeste_Decompiled.git

      - name: Build .csproj
        shell: cmd
        run: |
          cd Celeste_Decompiled\Celeste
          for %%i in (*.csproj) do (
            "C:\MyVS\MSBuild\Current\Bin\MSBuild.exe" %%i /p:Configuration=Release
          )

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: Binaries
          path: Celeste_Decompiled\Celeste\bin\Release\
